CREATE DATABASE menuDaBa;
USE menuDaBa;
CREATE TABLE menu_items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(50),
    calories INT
);
INSERT INTO menu_items (name, type, calories) VALUES
    ('Mercimek Çorbası', 'Çorba', 180),
    ('Ezogelin Çorbası', 'Çorba', 280),
    ('Tarhana Çorbası', 'Çorba', 150),
    ('Tel Şehriye Çorbası', 'Çorba', 175),
    ('Tutmaç Çorbası', 'Çorba', 175),
    ('Patates Çorbası', 'Çorba', 225),
    ('Sütlü Mısır Çorbası', 'Çorba', 180),
    ('Naneli Yoğurt Çorbası', 'Çorba', 175),
    ('Köy Usulü Mercimek', 'Çorba', 180),
    ('Toyga Çorbası', 'Çorba', 185),
    ('Yayla Çorbası', 'Çorba', 180),
    ('Domates Çorbası', 'Çorba', 166),
    ('Şafak Çorbası', 'Çorba', 175),
    ('Lebeniye Çorbası', 'Çorba', 175),
    ('Kremalı Mantar Çorbası', 'Çorba', 185),    
    ('Tavuk Döner', 'Ana Yemek', 350),
    ('Tire Köfte', 'Ana Yemek', 360),
    ('Tavuk Kavurma', 'Ana Yemek', 350),
    ('Bahçıvan Kebabı', 'Ana Yemek', 360),
    ('Nohut Yemeği', 'Ana Yemek', 330),
    ('Tavuk İskender', 'Ana Yemek', 360),
    ('Çiftlik Köfte', 'Ana Yemek', 355),
    ('Hamburger', 'Ana Yemek',365),
    ('Fırın Tavuk', 'Ana Yemek', 360),
    ('Gemici Usulü Kuru Fasulye', 'Ana Yemek', 330),
    ('Et Döner', 'Ana Yemek', 360),
    ('Körü Soslu Tavuk', 'Ana Yemek', 350),
    ('Mengen Köfte', 'Ana Yemek', 355),
    ('Tavuk Adana', 'Ana Yemek', 365),
    ('Ekşili Köfte', 'Ana Yemek', 350),
    ('Fırın Kanat', 'Ana Yemek', 355),    
    ('Kuru Köfte', 'Ana Yemek', 360),
    ('Misket Köfte', 'Ana Yemek', 350),
    ('Sebzeli Tavuk Sote', 'Ana Yemek', 355),   
    ('Bulgur Pilavı', 'Pilav', 276),
    ('Pirinç Pilavı', 'Pilav', 326),
    ('Erişte', 'Pilav', 330),
    ('Tel Şehriyeli Pirinç Pilavı', 'Pilav', 326),
    ('Napolitan Soslu Makarna', 'Pilav', 355),
    ('Arpa Şehriyeli Pirinç Pilavı', 'Pilav', 326),
    ('Mısırlı Pilav', 'Pilav', 330),
    ('Domates Soslu Makarna', 'Pilav', 355),    
    ('Çoban Salata', 'Salata', 100),
    ('Sezar Salata', 'Salata', 150),
    ('Sarı Burma', 'Salata', 250),
    ('Cacık', 'Salata', 125),
    ('Çiğ Köfte', 'Salata', 250),
    ('Kırmızı Lahana', 'Salata', 51),
    ('Mevsim Salata', 'Salata', 125),
    ('Üzüm Hoşafı', 'Salata', 150),
    ('Su Böreği', 'Salata', 355),
    ('Elma Dilim Patates', 'Salata', 330),
    ('Puding', 'Salata', 250),
    ('Havuç Dilimi', 'Salata', 250),
    ('Zeytinyağlı Brokoli', 'Salata', 175),
    ('Turşu ', 'Salata', 82),
    ('Çoban Salata', 'Salata', 100),
    ('Elma Kompostosu', 'Salata', 150),
    ('Sakızlı Muhallebi', 'Salata', 250),
    ('Haydari', 'Salata', 125),
    ('Çoban Salata', 'Salata', 100),
    ('Portakal', 'Salata', 55),
    ('Elma ', 'Salata', 55),     
    ('Ayran', 'İçecek', 35),
    ('Meyve Suyu', 'İçecek', 90),
    ('Nektar','İçecek', 100),
    ('Şeftali Suyu','İçecek', 100),
    ('Portakal Suyu','İçecek', 92),
    ('Limonata', 'İçecek', 100),
    ('Su', 'İçecek', 0),
    ('Kola','İçecek',122)
